services:
  kafka:
    container_name: kafka
    image: apache/kafka:latest
    hostname: kafka
    restart: unless-stopped
    ports:
      - "9091:29092" # 9091 -> <new port>
    environment:
      - TZ=Asia/Tehran
      - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf
    volumes:
      - kafka_data:/var/lib/kafka/data
      - ./kafka/config:/mnt/shared/config
      - ./kafka/secrets:/etc/kafka/secrets

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Tehran
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - AUTH_TYPE=LOGIN_FORM
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=pass
    depends_on:
      - kafka

volumes:
  kafka_data:
