services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=test
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: "pg_isready -U admin -d test"
      interval: 10s
      timeout: 5s
      retries: 2

volumes:
  postgres_data:
