services:
  proxy:
    container_name: proxy
    image: teddysun/v2ray:latest # teddysun/v2ray:latest -> teddysun/v2ray:5.51.2
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Tehran
    volumes:
      - ./proxy/config.json:/etc/v2ray/config.json
