services:
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: "redis-server --requirepass pass"
    healthcheck:
      test: "redis-cli ping"
      timeout: 5s
      retries: 2

volumes:
  redis_data:
